version: "4.0"

services:
  db:
    image: postgres:14.13-alpine3.20
    container_name: postgres_db
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - csp-network

volumes:
  db_data:

networks:
  csp-network: